[package]
name = "multiplatform_test"
publish = true
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/multiplatform_test/"
description = "A simple attribute macro to combine `#[test]` and `#[wasm_bindgen_test]`"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.74"
quote = "1.0.35"

[dev-dependencies]
env_logger = "0.11"
log = "0.4.21"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
wasm-bindgen-test = "0.3.0"
