[workspace]

members = [
    "benches",
    "hydro_cli",
    "hydro_cli_examples",
    "hydroflow",
    "hydroflow_cli_integration",
    "hydroflow_datalog",
    "hydroflow_datalog_core",
    "hydroflow_lang",
    "hydroflow_macro",
    "hydroflow_plus",
    "hydroflow_plus_test",
    "hydroflow_plus_test_macro",
    "lattices",
    "multiplatform_test",
    "pusherator",
    "relalg",
    "stageleft",
    "stageleft_macro",
    "stageleft_test",
    "stageleft_test_macro",
    "stageleft_tool",
    "variadics",
    "website_playground",
]

resolver = "2"

[profile.release]
strip = true      # Strip symbols from the binary
# Previously this was "z" to minimize docker binary size while sacrificing performance. But "z"
# doesn't make things that much smaller, `strip` is far more important for binary size. Use "3" for
# performance.
opt-level = 3
lto = "fat"

# There is only around 19GB of free space on the github free default runners
# without stripping the debug info, the build artefacts take up about 19GB
# with stripping the debug info, they take up about 5GB, so in ci we can use this profile to
# avoid running out of disk space.
[profile.cidev]
inherits = "dev"
strip = "debuginfo"

[profile.profile]
inherits = "release"
debug = 2
strip = "none"

[profile.dev.package.website_playground]
debug-assertions = false

[profile.release.package.website_playground]
opt-level = "s"
