[package]
description = "Gossip KV Library"
name = "gossip_kv"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
config = "0.14.0"
hostname = "0.4.0"
hydroflow = { path="../../hydroflow" }
rand = "0.8.5"
serde = "1.0.203"
serde_json = "1.0.117"
shlex = "1.3.0"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}

[[bin]]
name = "gossip_server"
path = "server/main.rs"

[[bin]]
name = "gossip_cli"
path = "cli/main.rs"

[lib]
name = "gossip_protocol"
path = "protocol/lib.rs"