[package]
name = "hydro_deploy"
publish = true
version = "0.8.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/hydro_deploy/"
description = "Hydro Deploy"

[dependencies]
anyhow = { version = "1.0.82", features = [ "backtrace" ] }
async-process = "2.0.0"
async-recursion = "1.0.0"
async-ssh2-lite = { version = "0.5.0", features = [ "tokio" ] }
async-trait = "0.1.54"
buildstructor = "0.5.0"
bytes = "1.1.0"
cargo_metadata = "0.18.0"
dunce = "1.0.0"
dyn-clone = "1.0.0"
futures = "0.3.0"
hydroflow_deploy_integration = { path = "../hydroflow_deploy_integration", version = "^0.9.0" }
indicatif = "0.17.0"
inferno = "0.11.0"
itertools = "0.10.0" # TODO(mingwei): remove when `iter_intersperse` is stabilized.
memo-map = "0.3.0"
nameof = "1.0.0"
nanoid = "0.4.0"
nix = { version = "0.29.0", features = [ "signal" ] }
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.115"
shell-escape = "0.1.0"
tempfile = "3.0.0"
tokio = { version = "1.29.0", features = [ "full" ] }
tokio-stream = { version = "0.1.3", default-features = false }
tokio-util = { version = "0.7.5", features = [ "compat", "io-util" ] }
