[package]
name = "variadics"
publish = true
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/variadics/"
description = "Variadic generics on stable Rust using tuple lists"

[dependencies]
sealed = "0.5"

[dev-dependencies]
trybuild = "1.0"