[build]
rustflags = [
    "-Zproc-macro-backtrace",
    "-Wunused_qualifications",
    # Flag to make build.rs scripts generate docs. Should only be used in this repository
    # internally, not by dependants.
    '--cfg=HYDROFLOW_GENERATE_DOCS',
    # https://github.com/rust-lang/rust-clippy/issues/10087
    ## TODO(mingwei): Need rust-analyzer support:
    # "-Aclippy::uninlined-format-args",
]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"