[package]
name = "stageleft_tool"
publish = true
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/stageleft_macro/"
repository = "https://github.com/hydro-project/hydro"
description = "Helper macros for the stageleft crate"

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
syn-inline-mod = "0.6.0"
quote = "1.0.35"
syn = { version = "2.0.46", features = [ "parsing", "extra-traits", "visit" ] }
proc-macro2 = "1.0.74"
sha2 = "0.10.0"
