[package]
name = "variadics_macro"
publish = true
version = "0.5.5"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/variadics/"
description = "Procedural macros for the `variadics` crate."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.63"
proc-macro-crate = "1.1.0"
quote = "1.0.0"
syn = { version = "2.0.0", features = [ "full", "parsing", "visit-mut" ] }
variadics = { path = "../variadics", version = "^0.0.5" }

[dev-dependencies]
insta = "1.7.1"
prettyplease = "0.2.20"
