[package]
name = "stageleft_test_macro"
publish = false
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true
path = "../stageleft_test/src/lib.rs"

[features]
default = ["macro"]
macro = []

[dependencies]
stageleft = { path = "../stageleft", version = "^0.2.0" }

[build-dependencies]
stageleft_tool = { path = "../stageleft_tool", version = "^0.1.0" }
