[package]
name = "topolotree"
publish = false
version = "0.0.0"
edition = "2021"

[[bin]]
name = "topolotree"
path = "src/main.rs"

[[bin]]
name = "pn"
path = "src/pn.rs"

[[bin]]
name = "pn_delta"
path = "src/pn_delta.rs"

[[bin]]
name = "latency_measure"
path = "src/latency_measure.rs"

[dependencies]
hydroflow = { path = "../hydroflow", features = [ "deploy_integration" ] }
hydroflow_datalog = { path = "../hydroflow_datalog" }

tokio = { version = "1.16", features = [ "full" ] }
serde = { version = "1", features = ["rc"] }
serde_json = "1"
rand = "0.8.5"

futures = "0.3.28"

[dev-dependencies]
tokio = { version = "1.16", features = [ "full", "test-util" ] }

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = "0.4.2"
